config/routes.rb
namespace :project_state do
  resources :summary, only: [:index]
  resources :users, only: [:show]
  resource :user, only: [:show]
  resources :state, only: [:show]
  resources :project_state_reports, only: [:index, :show, :update]
  resources :bank_holidays, only: [:index]
  get 'configure', action: :edit
  post 'configure', action: :edit
end

app/models/project_state_report.rb
class ProjectStateReport < ActiveRecord::Base
  unloadable
end

app/controllers/project_state/bank_holidays_controller.rb
class ProjectState::BankHolidaysController < ApplicationController

  unloadable

  def index
    year = Date.today.year
    @holidays = BankHoliday.where("holiday >= '?'",year).order(:holiday)
  end
end

app/controllers/project_state/project_state_reports_controller.rb
require 'logger'
require 'i18n'
require 'set'

require 'simple_xlsx_reader'
require 'project_state/utils'
require 'project_state/finance'
require 'project_state/snapshot'
require 'project_state/reports'

class ProjectState::ProjectStateReportsController < ApplicationController
  include ProjectStatePlugin::Utilities
  include ProjectStatePlugin::Reports

  unloadable

  def time_logged_by_group()
    @times = {}
    @projects = {}
    projlist = collectProjects(Setting.plugin_project_state['root_projects'])
    Project.where(id: projlist).each do |proj|
      @projects[proj.id] = proj
      @times[proj.id] = [0] * @ends.length
    end
    ind = 0
    # can't use "find_each" here because it is incompatible with "order"
    TimeEntry.where(spent_on: @from..(@ends[-1]-1)).order(:spent_on).each do |log|
      pid = log.project_id
      if projlist.include? pid
        while log.spent_on >= @ends[ind]
          ind += 1
        end
        @times[pid][ind] += log.hours
      end
    end
    totals = @times.keys.map{|k| @times[k].sum}.sort
    @threshold = totals[-10]
    @pids = @times.keys.sort{|a,b| @projects[a].name <=> @projects[b].name}
    @make_plot = true
  end

  def billable_time()
    leavelist = collectProjects('Leave')
    @users = {}
    @times = {}
    @absent = {}
    @frac = {}
    Group.find_by(lastname: 'Bioinformatics Core').users.each do |u|
      next unless u.status == Principal::STATUS_ACTIVE
      @users[u.id] = u
      @times[u.id] = [0] * @ends.length
      @absent[u.id] = [0] * @ends.length
      @frac[u.id] = [0] * @ends.length
    end
    ind = 0
    # can't use "find_each" here because it is incompatible with "order"
    TimeEntry.where(spent_on: @from..(@ends[-1]-1)).order(:spent_on).includes(:issue).each do |log|
      u = log.user_id
      next unless @users.has_key? u
      begin
        while log.spent_on >= @ends[ind]
          ind += 1
        end
      rescue ArgumentError => ae
        $pslog.warn("AE: log.id=#{log.id}  ind=#{ind}  ends[ind]=#{@ends[ind]}  elen=#{@ends.length}")
        $pslog.warn("AE: ends[-1]=#{@ends[-1]}  logdate=#{log.spent_on}")
        next
      end
      if leavelist.include? log.project_id
        @absent[u][ind] += log.hours
      else
        begin
          cc = log.issue.cost_centre
        rescue NoMethodError
          cc = log.project.cost_centre
        end
        if !cc.nil? && !(cc == "")
          @times[u][ind] += log.hours
        end
      end
    end
    (0..(@ends.length - 1)).each do |i|
      @users.keys.each do |u|
        wp = workproportion(u)
        wh = working_hours_by_proportion(@ends[i]-1,wp,@params['interval_type'])
        hours = @times[u][i]
        expected = wh - @absent[u][i]
        if expected > 0
          @frac[u][i] = (hours / expected * 1000).to_i / 10.0
        else
          @frac[u][i] = 0.0
        end
      end
    end
    @uids = @users.keys.sort{|a,b| @users[a].firstname <=> @users[b].firstname}
    @make_plot = true
  end

  def limit_changes()
    fields = CustomField.where(name: ['Hour Limit','State Timeout'])
    fmap = {}
    fields.each {|f| fmap[f.id] = f}
    jset = Journal.where(created_on: @from..(@to - 1))
    jdetails = JournalDetail.where(journal: jset)
    jmap = {}
    jset.each {|j| jmap[j.id] = j}
    @records = []
    jdetails.each do |jd|
      next unless ((jd.property == 'cf') && fmap.has_key?(jd.prop_key.to_i))
      j = jmap[jd.journal_id]
      iss = Issue.find(j.journalized_id)
      @records << {user: j.user, when: j.created_on, field: fmap[jd.prop_key.to_i].name,
                   from: jd.old_value, to: jd.value, state: iss.state, project: iss.project.name,
                   issue: iss.id, description: iss.subject, pid: iss.project.id}
    end
    @records.sort{|a,b| a[:when] <=> b[:when]}
    @make_plot = false
  end

  def number_in_state
    projects = collectProjects(Setting.plugin_project_state['root_projects'])
    snapshot = ProjectStatePlugin::Snapshot.new(projects)
    fid = CustomField.find_by(name: 'Project State').id.to_s
    today = Date.today
    ind = @ends.length - 1
    @counts = {}
    ProjectStatePlugin::Defaults::INTERESTING.each do |s|
      @counts[s] = []
    end
    Journal.where(created_on: @from..today).includes(:journalized,:details).order(created_on: :desc).each do |j|
      next if ! projects.include?(j.journalized.project_id)
      if j.created_on < @ends[ind]
        ind -= 1
        # following is a kludge to account for the possibility that this journal entry may in fact
        # be earlier than the current interval, i.e. that the current interval contains no
        # jounals.  This seems unlikely, but still... and this doesn't cope with two empty
        # intervals.  But that's even less likely.
        if ind > 0 && j.created_on < @ends[ind]
          $pslog.info("Number in State: empty interval ending #{@ends[ind+1]}")
          ind -= 1
        end
        snap = snapshot.snap_states()
        @counts.keys.each do |s|
          if snap.has_key?(s)
            @counts[s] << snap[s]
          else
            @counts[s] << 0
          end
        end
        break if ind < 0 # skip the first interval, because we report at the end, not start,so
                         # we don't need to run through these.  Could just not load them, but
                         # I'm confused enough already.
      end
      snapshot.journal(j.journalized,j)
    end
    @counts.keys.each do |s|
      @counts[s] = @counts[s].reverse
    end
    @make_plot = true
  end

  def state_by_analyst(state)
    projects = collectProjects(Setting.plugin_project_state['root_projects'])
    today = Date.today
    ind = @ends.length - 1
    snap = ProjectStatePlugin::Snapshot.new(projects)
    @counts = {}
    @analysts = {}
    Group.find_by(lastname: 'Bioinformatics Core').users.each do |u|
      @counts[u.id] = []
      @analysts[u.id] = u
    end
    Journal.where(created_on: @from..today).includes(:journalized,:details).order(created_on: :desc).each do |j|
      next if ! projects.include?(j.journalized.project_id)
      if j.created_on < @ends[ind]
        ind -= 1
        # following is a kludge to account for the possibility that this journal
        # entry may in fact be earlier than the current interval, i.e. that the
        # current interval contains no journals.  This seems unlikely, but
        # still... and this doesn't cope with two empty intervals.  But that's
        # even less likely.
        if ind > 0 && j.created_on < @ends[ind]
          $pslog.info("Number in State: empty interval ending #{@ends[ind+1]}")
          ind -= 1
        end
        shot = snap.snap_people(state)
        @counts.keys.each do |u|
          if shot.has_key?(u)
            @counts[u] << shot[u]
          else
            @counts[u] << 0
          end
        end
        break if ind < 0
      end
      snap.journal(j.journalized,j)
    end
    @counts.keys.each do |s|
      @counts[s] = @counts[s].reverse
    end
    @keys = @counts.keys.sort{|a,b| @analysts[a].firstname <=> @analysts[b].firstname}
    @make_plot = true
  end

  def active_by_analyst
    state_by_analyst("Active")
  end

  def hold_by_analyst
    state_by_analyst("Hold")
  end

  def collapse_project(p)
    p.children.each do |kid|
      collapse_project(kid)
      src = @times[kid.id]
      dst = @times[p.id]
      (0..(src.length-1)).each {|i| dst[i] = dst[i] + src[i]}
      @projects.delete(kid.id)
    end
  end

  def collapse_projects(rg_pid)
    @projects.each do |pid,proj|
      if proj.parent_id == rg_pid
        collapse_project(proj)
      end
    end
  end

  def hours_current_and_average_csv
    io = StringIO.new(string="",mode="w")
    io.printf(",#{@avg_tag},#{@cur_tag}\n")
    (0..(@labels.length-1)).each do |i|
      tag = I18n.transliterate(@labels[i])
      io.printf("#{tag},#{@average[i]},#{@current[i]}\n")
    end
    fn = "#{@report.view}_#{@cur_tag}.csv"
    send_data(io.string,filename: fn)
  end

  def hours_current_and_average
    @times = {}
    @projects = {}
    rg_pid = Project.find_by(name: 'Research Groups').id
    projlist = collectProjects(Setting.plugin_project_state['billable'])
    projlist.delete(rg_pid)
    Project.where(id: projlist).each do |proj|
      @projects[proj.id] = proj
      @times[proj.id] = [0.0] * @ends.length
    end
    ind = 0
    # can't use "find_each" here because it is incompatible with "order"
    TimeEntry.where(spent_on: @from..(@ends[-1]-1)).order(:spent_on).each do |log|
      pid = log.project_id
      if projlist.include? pid
        begin
          while log.spent_on >= @ends[ind]
            ind += 1
          end
        rescue
          $pslog.error("ind=#{ind} len=#{@ends.length} log=#{log.spent_on} to=#{@to} ends[-1]=#{@ends[-1]}")
          break
        end
        @times[pid][ind] += log.hours
      end
    end
    collapse_projects(rg_pid)
    @current = []
    @average = []
    @pids = @projects.keys.sort{|a,b| @projects[a].name <=> @projects[b].name}
    @current_show = []
    @average_show = []
    @labels_show = []
    @pids.each do |pid|
      @current << @times[pid][-1]
      @average << (@times[pid].sum / @times[pid].length).round(2)
      if @current[-1] >= 1.0 || @average[-1] >= 1.0
        @current_show << @current[-1]
        @average_show << @average[-1]
        @labels_show << @projects[pid].name
      end
    end
    @avg_tag = "#{@labels.length} #{@interval_label} average"
    @cur_tag = @labels[-1]
    @labels = @pids.each.map{|p| @projects[p].name}
    if @params['format'] == 'csv'
      hours_current_and_average_csv
    end
    @make_plot = true
  end

  class StateChange < Struct.new(:projid,:issue,:from,:to,:when)
  end

  def state_changes(iss,state_prop_key)
    changes = []
    iss.journals.includes(:details).each do |j|
      j.details.each do |jd|
        if jd.property == 'cf' && jd.prop_key == state_prop_key

app/controllers/project_state/state_controller.rb
require 'date'
require 'project_state/utils'
require 'bioinf_common/utils'
require 'project_state/issue_filter'

class ProjectState::StateController < ApplicationController
  include ProjectStatePlugin::Utilities
  include BiofinCommon::Utilities
  include ProjectStatePlugin::IssueFilter

  unloadable

  def show
    state = params[:id]

    projects = collectProjects(Setting.plugin_project_state['root_projects'])
    issues = collectIssues(projects).select{|i| i if i.state == state}
    if params[:report] == 'stark'
      issues = filter_issues(issues)
    else
      issues = filter_on_tracker(issues)
    end

    @issues = Hash.new
    @flags = Hash.new
    @users = Hash.new
    issues.each do |iss|
      u = iss.assigned_to_id
      @issues[u] = [] unless @issues.has_key? u
      @issues[u] << iss
      @flags[iss.id] = get_flags(iss)
      @users[u] = User.find(u) unless u.nil?
    end
    @usort = @issues.keys.sort{|a,b| a.nil? ? 1 : (b.nil? ? -1 : @users[a].firstname <=> @users[b].firstname)}
  end
end

app/controllers/project_state/summary_controller.rb
require 'date'
require 'project_state/defaults'
require 'project_state/utils'
require 'bioinf_common/utils'
require 'project_state/issue_filter'

class ProjectState::SummaryController < ApplicationController
  include ProjectStatePlugin::Utilities
  include BioinfCommon::Utilities
  include ProjectStatePlugin::IssueFilter

  unloadable

  def index
    @stark = params[:report] == 'stark'
    @states = ProjectStatePlugin::Defaults::INTERESTING

    projects = collectProjects(Setting.plugin_project_state['root_projects'])
    issues = collectIssues(projects)
    if @stark
      issues = filter_issues(issues)
    else
      issues = filter_on_tracker(issues)
    end

    @users = {}
    issues.each do |iss|
      @users[iss.assigned_to_id] = iss.assigned_to unless iss.assigned_to.nil?
    end
    @usort = @users.keys.sort{|a,b| a.nil? ? 1 : (b.nil? ? -1 : @users[a].firstname <=> @users[b].firstname)}
      
    @count = {}
    @flags = {}
    @users.keys.each do |u|
      @count[u] = Hash.new(0)
      @flags[u] = Hash.new(0)
    end
    @count[nil] = Hash.new(0) # for "unassigned" projects
    @flags[nil] = Hash.new(0)

    @rowcountsum = Hash.new(0)
    @rowflagsum = Hash.new(0)
    @colcountsum = Hash.new(0)
    @colflagsum = Hash.new(0)

    issues.each do |iss|
      @count[iss.assigned_to_id][iss.state] += 1
      @rowcountsum[iss.assigned_to_id] += 1
      @colcountsum[iss.state] += 1
      if is_flagged(iss)
        @flags[iss.assigned_to_id][iss.state] += 1
        @rowflagsum[iss.assigned_to_id] += 1
        @colflagsum[iss.state] += 1
      end
    end

    @totalsum = @rowcountsum.values.sum
    @totalflagsum = @rowflagsum.values.sum
  end

end

app/controllers/project_state/user_controller.rb
require 'date'
require 'project_state/utils'
require 'project_state/issue_filter'

class ProjectState::UserController < ApplicationController
  include ProjectStatePlugin::Utilities
  include ProjectStatePlugin::IssueFilter


  unloadable

  def show
    @user = params[:id] == '-1' ? nil : params[:id].to_i

    projects = collectProjects(Setting.plugin_project_state['root_projects'])
    issues = collectIssues(projects)
    issues = issues.select{|i| i if i.assigned_to_id == @user}
    
    if params[:report] == 'stark'
      issues = filter_issues(issues)
    end

    @issue_hash = Hash.new
    @flags = Hash.new
    issues.each do |iss|
      @issue_hash[iss.state] = [] unless @issue_hash.has_key? iss.state
      @issue_hash[iss.state] << iss
      @flags[iss.id] = get_flags(iss)
    end
  end
end

app/controllers/project_state/users_controller.rb
require 'date'
require 'project_state/utils'
require 'project_state/issue_filter'

class ProjectState::UsersController < ApplicationController
  include ProjectStatePlugin::Utilities
  include ProjectStatePlugin::IssueFilter


  unloadable

  def show
    has_id = params.has_key? :id
    if has_id
      @user = params[:id] == '-1' ? nil : params[:id].to_i
    else
      @user = User.current.id
    end
    
    if params[:all] == 'true'
      issues = collectAllOpenIssues()
      issues = issues.select{|i| i if i.assigned_to_id == @user}
      show_all = true 
    else
      projects = collectProjects(Setting.plugin_project_state['root_projects'])
      issues = collectIssues(projects)
      issues = issues.select{|i| i if i.assigned_to_id == @user}
      if params[:report] == 'stark'
        issues = filter_issues(issues)
      else
        issues = filter_on_tracker(issues)
      end
      show_all = false 
    end

    @issue_hash = Hash.new
    @flags = Hash.new
    issues.each do |iss|
      @issue_hash[iss.state] = [] unless @issue_hash.has_key? iss.state
      @issue_hash[iss.state] << iss
      @flags[iss.id] = get_flags(iss)
    end

    @toggle_text = l(:my_state_filtered_link)
    @toggle_link = "/project_state/user"
    if has_id
      @toggle_link += "?id=#{params[:id]}"
    end
    if not show_all
      @toggle_text = l(:my_state_all_link)
      @toggle_link += (has_id ? "&" : "?") + "all=true"
    end
  end
end

app/views/project_state/project_state_reports/_closing_waiting.html.erb
<h3>Closing and Waiting Issues</h3>

<table id="ps_waiting">
  <thead>
    <tr>
      <th onclick="sortTable(0)">Issue</th>
      <th onclick="sortTable(1)">Status</th>
      <th onclick="sortTable(3)">Date</th>
      <th onclick="sortTable(4)">Assignee</th>
      <th onclick="sortTable(5)">Reviewed</th>
      <th onclick="sortTable(6)">Title</th>
    </tr>
  </thead>
  <tbody>
    <% @waiting.each do |iss| %>
      <% u = @dates[iss.id] %>
      <tr>
        <td><a href="<%= issue_url(iss.id) %>"><%= iss.id %></a></td>
        <td><%= @statuses.fetch(u.status) %></td>
        <td><%= u.entered_on.strftime("%Y-%b-%d") %></td>
        <td class="hidden"><%= u.entered_on%></td>
        <td><%= iss.assigned_to.nil? ? "unassigned" : iss.assigned_to.firstname %></td>
        <td><%= u.reviewed %></td>
        <td><%= iss.subject %></td>
        <% if iss.status_id != u.status %>
          <td>(now <%= IssueStatus.find_by(id: iss.status_id).name %>)</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/project_state/project_state_reports/_finance_report.html.erb
<h3>Tabular View</h3>
<p><%= link_to "CSV", project_state_project_state_report_path(@report,
                   format: 'csv',
                   report_fin_interval: @params['report_fin_interval'],
                   spreadsheet: @tmp_spreadsheet),
            method: :patch %> | <span style="font-size: x-large;">Month: <%= @default_month %></span></p>

<table id="ps_counts">
  <thead>
    <tr><th>Grant</th><th>Code</th><th>Hours</th></tr>
  </thead>
  <tbody>
    <% @grants.each_with_index do |g,i| %>
      <tr>
        <td><%= g %></td>
        <td><%= @codes[i] %></td>
        <td><%= @costs[i] == 0 ? "" : @costs[i] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @orphans.length > 0 %>
<h3>Orphans</h3>
<table id="ps_counts">
  <thead>
    <tr><th>Code</th><th>Project</th><th>Issue</th><th>User</th><th>Activity</th><th>Hours</th><th>Date</th><th>Subject</th></tr>
  </th>
  <tbody>
    <% @orphans.each do |orph| %>
      <tr>
        <td><%= orph.code %></td>
        <td><%= orph.project %></td>
        <td><a href="<%= issue_url(orph.issue) %>"><%= orph.issue %></a></td>
        <td><%= orph.user %></td>
        <td><%= orph.activity %></td>
        <td><%= orph.hours %></td>
        <td><%= orph.date %></td>
        <td><%= orph.descr %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/project_state/project_state_reports/_form_charging.html.erb
<div id="project_state_date_form">
  <%= form_for([:project_state, @report], method: 'patch', html: {multipart: true}) do %>
  <fieldset>

    <div>
      <label for=:report_fin_interval><%= l(:report_fin_label) %></label>
      <%= select_tag(:report_fin_interval, options_for_select(@fin_list,@default_month)) %>
    </div>

    <div>
      <label for=:report_fin_file><%= l(:report_fin_fileupload) %></label>
      <%= file_field_tag 'spreadsheet' %>
    </div>

    <div>
      <%= submit_tag(l(:report_submit)) %>
    </div>

  </fieldset>
  <% end %>
</div>

app/views/project_state/project_state_reports/_form_dates.html.erb
<div id="project_state_date_form">
  <%= form_for([:project_state, @report], method: 'patch') do %>
  <fieldset>
    <div><div><%= radio_button_tag :date_type, '1', (@params['date_type']=='1' || (! @params.has_key?('date_type'))) %>
         <label class="noblock" for=:date_type_1><%= l(:report_date_type_fixed) %></label></div>
         <%= select_tag(:period_type, options_for_select(@periods,@params['period_type'])) %>
    </div>
    <div><%= radio_button_tag :date_type, '2', @params['date_type']=='2' %>
         <label class="noblock" for=:date_type_2><%= l(:report_date_type_open) %></label>
         <label for=:report_date_from><%= l(:report_date_from) %></label>
         <%= date_field_tag :report_date_from, value=@params['report_date_from'],  options={size: 10} %><%= calendar_for(:report_date_from) %>
         <label for='report_date_to'><%= l(:report_date_to) %></label>
         <%= date_field_tag :report_date_to, value=@params['report_date_to'], options={size: 10} %><%= calendar_for(:report_date_to) %>
    </div>
    <% if @report.want_interval %>
      <div>
        <label><%= l(:label_interval_type) %></label>
        <%= select_tag(:interval_type, options_for_select(@intervals,@params['interval_type'])) %>
      </div>
    <% end %>
    <div>
      <%= submit_tag(l(:report_submit)) %>
    </div>
    <div>
      <p><%=raw l(:report_date_interpretation) %></p>
    </div>
  </fieldset>
  <% end %>
</div>

app/views/project_state/project_state_reports/_form_year.html.erb
<div id="project_state_form">
  <%= form_for([:project_state, @report], method: 'patch') do %>
  year: <%= text_field_tag(:year,value=@year,options={size: 6}) %>
  <%= submit_tag(l(:report_submit)) %>
  <% end %>
</div>

app/views/project_state/project_state_reports/_hold_by_analyst.html.erb
<%= render partial: "state_by_analyst" %>

app/views/project_state/project_state_reports/_hours_current_and_average.html.erb
<script>
var chart = new Highcharts.Chart({
        chart: {
            renderTo: 'chart_container',
            type: 'column'
        },
        plotOptions: {
          series: {
            animation: false
          }
        },
        title: {
            text: '<%= @report.name + ": #{@intervaltitle}" %>'
        },
        xAxis: {
            categories: <%=raw @labels_show %>
        },
        yAxis: {
            min: 0,
            title: {
                text: '<%= l(:report_bygroup_yaxis) %>'
            }
        },
        series: [
            { name: '<%= @avg_tag %>',
              data: <%= @average_show %>
            },
            { name: '<%= @cur_tag %>',
              data: <%= @current_show %> }
        ],
        exporting: {
           scale: 3,
           fallbackToExportServer: false
       }

});
</script>

<h3>Tabular View</h3>
<%= link_to "CSV", project_state_project_state_report_path(@report,
                   format: 'csv',
                   date_type: @params['date_type'],
                   period_type: @params['period_type'],
                   report_date_from: @params['report_date_from'],
                   report_date_to: @params['report_date_to'],
                   interval_type: @params['interval_type']),
            method: :patch %>

<table id="ps_counts">
  <thead>
    <tr><th></th><th><%= @avg_tag %></th><th><%= @cur_tag %></th></tr>
  </thead>
  <tbody>
    <% (0..(@pids.length-1)).each do |i| %>
      <tr>
        <td><%= @projects[@pids[i]].name %></td>
        <td><%= @average[i] %></td>
        <td><%= @current[i] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/project_state/project_state_reports/_limit_changes.html.erb
<h3><%= l(:report_limit_changes) %></h3>

<table id="ps_limit_changes">
  <thead>
    <tr><th>Who</th><th>When</th><th>What</th><th>From</th><th>To</th><th>State</th><th>Project</th><th>Issue</th><th>Description</th></tr>
  </thead>
  <tbody>
    <% @records.each do |r| %>
      <tr>
        <td><%= r[:user].firstname %></td>
        <td><%= r[:when] %></td>
        <td><%= r[:field] %></td>
        <td><%= r[:from] %></td>
        <td><%= r[:to] %></td>
        <td><%= r[:state] %></td>
        <td><a href="<%= project_url(r[:pid]) %>"><%= r[:project] %></a></td>
        <td><a href="<%= issue_url(r[:issue]) %>"><%= r[:issue] %></a></td>
        <td><%= r[:description] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/project_state/project_state_reports/_time_waiting.html.erb
<script>
var chart = new Highcharts.Chart({
        chart: {
            type: 'scatter',
            renderTo: 'chart_container'
        },
        title: {
            text: '<%= @report.name + ": #{@intervaltitle}" %>'
        },
        xAxis: {
            categories: <%=raw @labels %>
        },
        yAxis: {
            title: {
                text: '<%= l(:report_waiting_yaxis) %>'
            },
            floor: 0
        },
        plotOptions: {
          series: {
            animation: false,
            point: {
              events: {
                click: function(e) {
                  window.open("/issues/"+this.word);
                }
              }
            }
          }
        },
        tooltip: {
          pointFormat: "Issue: {point.word}  Days: {point.y}"
        },
        series: [
            { name: '<%= l(:report_waiting_ready) %>',
              data: [ <%=raw @data_ready %> ],
              visible: true
            },
            { name: '<%= l(:report_waiting_pend) %>',
              data: [ <%=raw @data_pend %> ],
              visible: true
            },
            { name: '<%= l(:report_waiting_hold) %>',
              data: [ <%=raw @data_hold %> ],
              visible: true
            }
        ],
        exporting: {
           scale: 3,
           fallbackToExportServer: false
       }

});
</script>

<h3>Tabular View</h3>

<table id="ps_waiting">
  <thead>
    <tr>
      <th><%= l(:text_issue) %></th>
      <th><%= l(:report_waiting_days_in_state) %></th>
      <th><%= l(:report_waiting_entered_on) %></th>
      <th><%= l(:report_waiting_left_on) %></th>
      <th><%= l(:text_project) %></th>
      <th><%= l(:text_subject) %></th>
    </tr>
  </thead>
  <tbody>
    <% (0..(@labels.length-1)).each do |i| %>
      <tr id="wait_date_line"><th colspan=6><%= @labels[i] %></th></tr>
      <% if @ready_lists[i].length > 0 %>
        <tr id="wait_state_line"><th colspan=6>Ready</th></tr>
        <% @ready_lists[i].each do |ent| %>
          <tr>
            <td><a href="<%= issue_url(ent.issue.id) %>"><%= ent.issue.id %></a></td>
            <td class="counts"><%= ent.days %></td>
            <td><%= ent.entered_on %></td>
            <td><%= ent.left_on %></td>
            <td><a href="<%= project_url(ent.issue.project_id) %>"><%= ent.issue.project.name %></a></td>
            <td><%= ent.issue.subject.truncate(70) %></td>
          </tr>
        <% end %>
      <% end %>
      <% if @pend_lists[i].length > 0 %>
        <tr id="wait_state_line"><th colspan=6>Pending</th></tr>
        <% @pend_lists[i].each do |ent| %>
          <tr>
            <td><a href="<%= issue_url(ent.issue.id) %>"><%= ent.issue.id %></a></td>
            <td class="counts"><%= ent.days %></td>
            <td><%= ent.entered_on %></td>
            <td><%= ent.left_on %></td>
            <td><a href="<%= project_url(ent.issue.project_id) %>"><%= ent.issue.project.name %></a></td>
            <td><%= ent.issue.subject.truncate(70) %></td>
          </tr>
        <% end %>
      <% end %>
      <% if @hold_lists[i].length > 0 %>
        <tr id="wait_state_line"><th colspan=6>On Hold</th></tr>
        <% @hold_lists[i].each do |ent| %>
          <tr>
            <td><a href="<%= issue_url(ent.issue.id) %>"><%= ent.issue.id %></a></td>
            <td class="counts"><%= ent.days %></td>
            <td><%= ent.entered_on %></td>
            <td><%= ent.left_on %></td>
            <td><a href="<%= project_url(ent.issue.project_id) %>"><%= ent.issue.project.name %></a></td>
            <td><%= ent.issue.subject.truncate(70) %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>