config/routes.rb
namespace :project_state do
  resources :summary, only: [:index]
  resources :users, only: [:show]
  resource :user, only: [:show]
  resources :state, only: [:show]
  resources :project_state_reports, only: [:index, :show, :update]
  resources :bank_holidays, only: [:index]
  get 'configure', action: :edit
  post 'configure', action: :edit
end

app/views/settings/_project_state_settings.html.erb
<p><%= l(:settings_help_text_top) %></p>
<p><label for='settings_root_projects'><span title="<%= l(:settings_root_projects_descr) %>"><%= l(:settings_root_projects_label) %></span></label>
   <%= text_field_tag 'settings[root_projects]', @settings['root_projects'] %>
</p>

<p><label for='settings_alert_logins'><span title="<%= l(:settings_alert_logins_descr) %>"><%= l(:settings_alert_logins_label) %></span></label>
   <%= text_field_tag 'settings[alert_logins]', @settings['alert_logins'] %>
</p>

<p><label for='settings_filter_trackers'><span title="<%= l(:settings_filter_trackers_descr) %>"><%= l(:settings_filter_trackers_label) %></span></label>
   <%= text_field_tag 'settings[filter_trackers]', @settings['filter_trackers'] %>
</p>

<p><label for='settings_filter_projects'><span title="<%= l(:settings_filter_projects_descr) %>"><%= l(:settings_filter_projects_label) %></span></label>
   <%= text_field_tag 'settings[filter_projects]', @settings['filter_projects'] %>
</p>

<p><label for='settings_filter_keepers'><span title="<%= l(:settings_filter_keepers_descr) %>"><%= l(:settings_filter_keepers_label) %></span></label>
   <%= text_field_tag 'settings[filter_keepers]', @settings['filter_keepers'] %>
</p>

<p><label for='settings_ignore_trackers'><span title="<%= l(:settings_ignore_trackers_descr) %>"><%= l(:settings_ignore_trackers_label) %></span></label>
   <%= text_field_tag 'settings[ignore_trackers]', @settings['ignore_trackers'] %>
</p>

<p><label for='settings_no_researcher'><span title="<%= l(:settings_no_researcher_descr) %>"><%= l(:settings_no_researcher_label) %></span></label>
   <%= text_field_tag 'settings[no_researcher]', @settings['no_researcher'] %>
</p>

<p><label for='settings_holiday_url'><span title="<%= l(:settings_holiday_url_descr) %>"><%= l(:settings_holiday_url_label) %></span></label>
   <%= text_field_tag 'settings[holiday_url]', @settings['holiday_url'] %>
</p>

<p><label for='settings_log_file'><span title="<%= l(:settings_log_file_descr) %>"><%= l(:settings_log_file_label) %></span></label>
   <%= text_field_tag 'settings[log_file]', @settings['log_file'] %>
</p>

<p><label for='settings_non_chargeable'><span title="<%= l(:settings_non_chargeable_descr) %>"><%= l(:settings_non_chargeable_label) %></span></label>
   <%= text_field_tag 'settings[non_chargeable]', @settings['non_chargeable'] %>
</p>

<p><label for='settings_billable'><span title="<%= l(:settings_billable_descr) %>"><%= l(:settings_billable_label) %></span></label>
   <%= text_field_tag 'settings[billable]', @settings['billable'] %>
</p>

<p><a href="/project_state/configure"><%= l(:conf_link) %></a></p>